# Generated by Django 4.2.13 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('payment_confirmed', 'Payment Confirmed'), ('low_stock', 'Low Stock Alert'), ('review_approved', 'Review Approved')], max_length=30),
        ),
    ]
