# Generated by Django 4.2.13 on 2026-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='saved_for_later',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
