# Generated by Django 4.2.13 on 2026-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('easypaisa', 'Easypaisa'), ('card', 'Credit / Debit Card')], max_length=15),
        ),
    ]
