# Generated by Django 4.2.13 on 2026-06-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('return', 'Return'), ('refund', 'Refund'), ('exchange', 'Exchange')], max_length=10)),
                ('reason', models.CharField(choices=[('wrong_size', 'Wrong size / does not fit'), ('damaged', 'Arrived damaged or defective'), ('wrong_item', 'Received the wrong item'), ('not_as_described', 'Not as described'), ('changed_mind', 'Changed my mind'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='requested', max_length=10)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
            ],
            options={
                'db_table': 'order_returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
