# Generated by Django 4.2.13 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
